using System;
using Domain.Entities.Models;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities
{
    /// <summary>
    /// BooBitSeeder, here we can generate the
    /// default values of the database
    /// </summary>
    public  class BoomSeeder
    {
        /// <summary>
        /// Seeder to add all the countries
        /// around the world
        /// </summary>
        /// <param name="modelBuilder"></param>
        public static void SeedCountries(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Country>().HasData(
                new Country {Id=1, Code= "AFG", Name= "Afghanistan", Active= true },
                new Country {Id=2, Code= "ALA", Name= "Aland Islands", Active= true },
                new Country {Id=3, Code= "ALB", Name= "Albania", Active= true },
                new Country {Id=4, Code= "DZA", Name= "Algeria", Active= true },
                new Country {Id=5, Code= "ASM", Name= "American Samoa", Active= true },
                new Country {Id=6, Code= "AND", Name= "Andorra", Active= true },
                new Country {Id=7, Code= "AGO", Name= "Angola", Active= true },
                new Country {Id=8, Code= "AIA", Name= "Anguilla", Active= true },
                new Country {Id=9, Code= "ATA", Name= "Antarctica", Active= true },
                new Country {Id=10, Code= "ATG", Name= "Antigua and Barbuda", Active= true },
                new Country {Id=11, Code= "ARG", Name= "Argentina", Active= true },
                new Country {Id=12, Code= "ARM", Name= "Armenia", Active= true },
                new Country {Id=13, Code= "ABW", Name= "Aruba", Active= true },
                new Country {Id=14, Code= "AUS", Name= "Australia", Active= true },
                new Country {Id=15, Code= "AUT", Name= "Austria", Active= true },
                new Country {Id=16, Code= "AZE", Name= "Azerbaijan", Active= true },
                new Country {Id=17, Code= "BHS", Name= "Bahamas", Active= true },
                new Country {Id=18, Code= "BHR", Name= "Bahrain", Active= true },
                new Country {Id=19, Code= "BGD", Name= "Bangladesh", Active= true },
                new Country {Id=20, Code= "BRB", Name= "Barbados", Active= true },
                new Country {Id=21, Code= "BLR", Name= "Belarus", Active= true },
                new Country {Id=22, Code= "BEL", Name= "Belgium", Active= true },
                new Country {Id=23, Code= "BLZ", Name= "Belize", Active= true },
                new Country {Id=24, Code= "BEN", Name= "Benin", Active= true },
                new Country {Id=25, Code= "BMU", Name= "Bermuda", Active= true },
                new Country {Id=26, Code= "BTN", Name= "Bhutan", Active= true },
                new Country {Id=27, Code= "BOL", Name= "Bolivia", Active= true },
                new Country {Id=28, Code= "BIH", Name= "Bosnia and Herzegovina", Active= true },
                new Country {Id=29, Code= "BWA", Name= "Botswana", Active= true },
                new Country {Id=30, Code= "BVT", Name= "Bouvet Island", Active= true },
                new Country {Id=31, Code= "BRA", Name= "Brazil", Active= true },
                new Country {Id=32, Code= "VGB", Name= "British Virgin Islands", Active= true },
                new Country {Id=33, Code= "IOT", Name= "British Indian Ocean Territory", Active= true },
                new Country {Id=34, Code= "BRN", Name= "Brunei Darussalam", Active= true },
                new Country {Id=35, Code= "BGR", Name= "Bulgaria", Active= true },
                new Country {Id=36, Code= "BFA", Name= "Burkina Faso", Active= true },
                new Country {Id=37, Code= "BDI", Name= "Burundi", Active= true },
                new Country {Id=38, Code= "KHM", Name= "Cambodia", Active= true },
                new Country {Id=39, Code= "CMR", Name= "Cameroon", Active= true },
                new Country {Id=40, Code= "CAN", Name= "Canada", Active= true },
                new Country {Id=41, Code= "CPV", Name= "Cape Verde", Active= true },
                new Country {Id=42, Code= "CYM", Name= "Cayman Islands", Active= true },
                new Country {Id=43, Code= "CAF", Name= "Central African Republic", Active= true },
                new Country {Id=44, Code= "TCD", Name= "Chad", Active= true },
                new Country {Id=45, Code= "CHL", Name= "Chile", Active= true },
                new Country {Id=46, Code= "CHN", Name= "China", Active= true },
                new Country {Id=47, Code= "HKG", Name= "Hong Kong, SAR China", Active= true },
                new Country {Id=48, Code= "MAC", Name= "Macao, SAR China", Active= true },
                new Country {Id=49, Code= "CXR", Name= "Christmas Island", Active= true },
                new Country {Id=50, Code= "CCK", Name= "Cocos (Keeling) Islands", Active= true },
                new Country {Id=51, Code= "COL", Name= "Colombia", Active= true },
                new Country {Id=52, Code= "COM", Name= "Comoros", Active= true },
                new Country {Id=53, Code= "COG", Name= "Congo (Brazzaville)", Active= true },
                new Country {Id=54, Code= "COD", Name= "Congo, (Kinshasa)", Active= true },
                new Country {Id=55, Code= "COK", Name= "Cook Islands", Active= true },
                new Country {Id=56, Code= "CRI", Name= "Costa Rica", Active= true },
                new Country {Id=57, Code= "CIV", Name= "Côte d'Ivoire", Active= true },
                new Country {Id=58, Code= "HRV", Name= "Croatia", Active= true },
                new Country {Id=59, Code= "CUB", Name= "Cuba", Active= true },
                new Country {Id=60, Code= "CYP", Name= "Cyprus", Active= true },
                new Country {Id=61, Code= "CZE", Name= "Czech Republic", Active= true },
                new Country {Id=62, Code= "DNK", Name= "Denmark", Active= true },
                new Country {Id=63, Code= "DJI", Name= "Djibouti", Active= true },
                new Country {Id=64, Code= "DMA", Name= "Dominica", Active= true },
                new Country {Id=65, Code= "DOM", Name= "Dominican Republic", Active= true },
                new Country {Id=66, Code= "ECU", Name= "Ecuador", Active= true },
                new Country {Id=67, Code= "EGY", Name= "Egypt", Active= true },
                new Country {Id=68, Code= "SLV", Name= "El Salvador", Active= true },
                new Country {Id=69, Code= "GNQ", Name= "Equatorial Guinea", Active= true },
                new Country {Id=70, Code= "ERI", Name= "Eritrea", Active= true },
                new Country {Id=71, Code= "EST", Name= "Estonia", Active= true },
                new Country {Id=72, Code= "ETH", Name= "Ethiopia", Active= true },
                new Country {Id=73, Code= "FLK", Name= "Falkland Islands (Malvinas)", Active= true },
                new Country {Id=74, Code= "FRO", Name= "Faroe Islands", Active= true },
                new Country {Id=75, Code= "FJI", Name= "Fiji", Active= true },
                new Country {Id=76, Code= "FIN", Name= "Finland", Active= true },
                new Country {Id=77, Code= "FRA", Name= "France", Active= true },
                new Country {Id=78, Code= "GUF", Name= "French Guiana", Active= true },
                new Country {Id=79, Code= "PYF", Name= "French Polynesia", Active= true },
                new Country {Id=80, Code= "ATF", Name= "French Southern Territories", Active= true },
                new Country {Id=81, Code= "GAB", Name= "Gabon", Active= true },
                new Country {Id=82, Code= "GMB", Name= "Gambia", Active= true },
                new Country {Id=83, Code= "GEO", Name= "Georgia", Active= true },
                new Country {Id=84, Code= "DEU", Name= "Germany", Active= true },
                new Country {Id=85, Code= "GHA", Name= "Ghana", Active= true },
                new Country {Id=86, Code= "GIB", Name= "Gibraltar", Active= true },
                new Country {Id=87, Code= "GRC", Name= "Greece", Active= true },
                new Country {Id=88, Code= "GRL", Name= "Greenland", Active= true },
                new Country {Id=89, Code= "GRD", Name= "Grenada", Active= true },
                new Country {Id=90, Code= "GLP", Name= "Guadeloupe", Active= true },
                new Country {Id=91, Code= "GUM", Name= "Guam", Active= true },
                new Country {Id=92, Code= "GTM", Name= "Guatemala", Active= true },
                new Country {Id=93, Code= "GGY", Name= "Guernsey", Active= true },
                new Country {Id=94, Code= "GIN", Name= "Guinea", Active= true },
                new Country {Id=95, Code= "GNB", Name= "Guinea-Bissau", Active= true },
                new Country {Id=96, Code= "GUY", Name= "Guyana", Active= true },
                new Country {Id=97, Code= "HTI", Name= "Haiti", Active= true },
                new Country {Id=98, Code= "HMD", Name= "Heard and Mcdonald Islands", Active= true },
                new Country {Id=99, Code= "VAT", Name= "Holy See (Vatican City State)", Active= true },
                new Country {Id=100, Code= "HND", Name= "Honduras", Active= true },
                new Country {Id=101, Code= "HUN", Name= "Hungary", Active= true },
                new Country {Id=102, Code= "ISL", Name= "Iceland", Active= true },
                new Country {Id=103, Code= "IND", Name= "India", Active= true },
                new Country {Id=104, Code= "IDN", Name= "Indonesia", Active= true },
                new Country {Id=105, Code= "IRN", Name= "Iran, Islamic Republic of", Active= true },
                new Country {Id=106, Code= "IRQ", Name= "Iraq", Active= true },
                new Country {Id=107, Code= "IRL", Name= "Ireland", Active= true },
                new Country {Id=108, Code= "IMN", Name= "Isle of Man", Active= true },
                new Country {Id=109, Code= "ISR", Name= "Israel", Active= true },
                new Country {Id=110, Code= "ITA", Name= "Italy", Active= true },
                new Country {Id=111, Code= "JAM", Name= "Jamaica", Active= true },
                new Country {Id=112, Code= "JPN", Name= "Japan", Active= true },
                new Country {Id=113, Code= "JEY", Name= "Jersey", Active= true },
                new Country {Id=114, Code= "JOR", Name= "Jordan", Active= true },
                new Country {Id=115, Code= "KAZ", Name= "Kazakhstan", Active= true },
                new Country {Id=116, Code= "KEN", Name= "Kenya", Active= true },
                new Country {Id=117, Code= "KIR", Name= "Kiribati", Active= true },
                new Country {Id=118, Code= "PRK", Name= "Korea (North)", Active= true },
                new Country {Id=119, Code= "KOR", Name= "Korea (South)", Active= true },
                new Country {Id=120, Code= "KWT", Name= "Kuwait", Active= true },
                new Country {Id=121, Code= "KGZ", Name= "Kyrgyzstan", Active= true },
                new Country {Id=122, Code= "LAO", Name= "Lao PDR", Active= true },
                new Country {Id=123, Code= "LVA", Name= "Latvia", Active= true },
                new Country {Id=124, Code= "LBN", Name= "Lebanon", Active= true },
                new Country {Id=125, Code= "LSO", Name= "Lesotho", Active= true },
                new Country {Id=126, Code= "LBR", Name= "Liberia", Active= true },
                new Country {Id=127, Code= "LBY", Name= "Libya", Active= true },
                new Country {Id=128, Code= "LIE", Name= "Liechtenstein", Active= true },
                new Country {Id=129, Code= "LTU", Name= "Lithuania", Active= true },
                new Country {Id=130, Code= "LUX", Name= "Luxembourg", Active= true },
                new Country {Id=131, Code= "MKD", Name= "Macedonia, Republic of", Active= true },
                new Country {Id=132, Code= "MDG", Name= "Madagascar", Active= true },
                new Country {Id=133, Code= "MWI", Name= "Malawi", Active= true },
                new Country {Id=134, Code= "MYS", Name= "Malaysia", Active= true },
                new Country {Id=135, Code= "MDV", Name= "Maldives", Active= true },
                new Country {Id=136, Code= "MLI", Name= "Mali", Active= true },
                new Country {Id=137, Code= "MLT", Name= "Malta", Active= true },
                new Country {Id=138, Code= "MHL", Name= "Marshall Islands", Active= true },
                new Country {Id=139, Code= "MTQ", Name= "Martinique", Active= true },
                new Country {Id=140, Code= "MRT", Name= "Mauritania", Active= true },
                new Country {Id=141, Code= "MUS", Name= "Mauritius", Active= true },
                new Country {Id=142, Code= "MYT", Name= "Mayotte", Active= true },
                new Country {Id=143, Code= "MEX", Name= "Mexico", Active= true },
                new Country {Id=144, Code= "FSM", Name= "Micronesia, Federated States of", Active= true },
                new Country {Id=145, Code= "MDA", Name= "Moldova", Active= true },
                new Country {Id=146, Code= "MCO", Name= "Monaco", Active= true },
                new Country {Id=147, Code= "MNG", Name= "Mongolia", Active= true },
                new Country {Id=148, Code= "MNE", Name= "Montenegro", Active= true },
                new Country {Id=149, Code= "MSR", Name= "Montserrat", Active= true },
                new Country {Id=150, Code= "MAR", Name= "Morocco", Active= true },
                new Country {Id=151, Code= "MOZ", Name= "Mozambique", Active= true },
                new Country {Id=152, Code= "MMR", Name= "Myanmar", Active= true },
                new Country {Id=153, Code= "NAM", Name= "Namibia", Active= true },
                new Country {Id=154, Code= "NRU", Name= "Nauru", Active= true },
                new Country {Id=155, Code= "NPL", Name= "Nepal", Active= true },
                new Country {Id=156, Code= "NLD", Name= "Netherlands", Active= true },
                new Country {Id=157, Code= "ANT", Name= "Netherlands Antilles", Active= true },
                new Country {Id=158, Code= "NCL", Name= "New Caledonia", Active= true },
                new Country {Id=159, Code= "NZL", Name= "New Zealand", Active= true },
                new Country {Id=160, Code= "NIC", Name= "Nicaragua", Active= true },
                new Country {Id=161, Code= "NER", Name= "Niger", Active= true },
                new Country {Id=162, Code= "NGA", Name= "Nigeria", Active= true },
                new Country {Id=163, Code= "NIU", Name= "Niue", Active= true },
                new Country {Id=164, Code= "NFK", Name= "Norfolk Island", Active= true },
                new Country {Id=165, Code= "MNP", Name= "Northern Mariana Islands", Active= true },
                new Country {Id=166, Code= "NOR", Name= "Norway", Active= true },
                new Country {Id=167, Code= "OMN", Name= "Oman", Active= true },
                new Country {Id=168, Code= "PAK", Name= "Pakistan", Active= true },
                new Country {Id=169, Code= "PLW", Name= "Palau", Active= true },
                new Country {Id=170, Code= "PSE", Name= "Palestinian Territory", Active= true },
                new Country {Id=171, Code= "PAN", Name= "Panama", Active= true },
                new Country {Id=172, Code= "PNG", Name= "Papua New Guinea", Active= true },
                new Country {Id=173, Code= "PRY", Name= "Paraguay", Active= true },
                new Country {Id=174, Code= "PER", Name= "Peru", Active= true },
                new Country {Id=175, Code= "PHL", Name= "Philippines", Active= true },
                new Country {Id=176, Code= "PCN", Name= "Pitcairn", Active= true },
                new Country {Id=177, Code= "POL", Name= "Poland", Active= true },
                new Country {Id=178, Code= "PRT", Name= "Portugal", Active= true },
                new Country {Id=179, Code= "PRI", Name= "Puerto Rico", Active= true },
                new Country {Id=180, Code= "QAT", Name= "Qatar", Active= true },
                new Country {Id=181, Code= "REU", Name= "Réunion", Active= true },
                new Country {Id=182, Code= "ROU", Name= "Romania", Active= true },
                new Country {Id=183, Code= "RUS", Name= "Russian Federation", Active= true },
                new Country {Id=184, Code= "RWA", Name= "Rwanda", Active= true },
                new Country {Id=185, Code= "BLM", Name= "Saint-Barthélemy", Active= true },
                new Country {Id=186, Code= "SHN", Name= "Saint Helena", Active= true },
                new Country {Id=187, Code= "KNA", Name= "Saint Kitts and Nevis", Active= true },
                new Country {Id=188, Code= "LCA", Name= "Saint Lucia", Active= true },
                new Country {Id=189, Code= "MAF", Name= "Saint-Martin (French part)", Active= true },
                new Country {Id=190, Code= "SPM", Name= "Saint Pierre and Miquelon", Active= true },
                new Country {Id=191, Code= "VCT", Name= "Saint Vincent and Grenadines", Active= true },
                new Country {Id=192, Code= "WSM", Name= "Samoa", Active= true },
                new Country {Id=193, Code= "SMR", Name= "San Marino", Active= true },
                new Country {Id=194, Code= "STP", Name= "Sao Tome and Principe", Active= true },
                new Country {Id=195, Code= "SAU", Name= "Saudi Arabia", Active= true },
                new Country {Id=196, Code= "SEN", Name= "Senegal", Active= true },
                new Country {Id=197, Code= "SRB", Name= "Serbia", Active= true },
                new Country {Id=198, Code= "SYC", Name= "Seychelles", Active= true },
                new Country {Id=199, Code= "SLE", Name= "Sierra Leone", Active= true },
                new Country {Id=200, Code= "SGP", Name= "Singapore", Active= true },
                new Country {Id=201, Code= "SVK", Name= "Slovakia", Active= true },
                new Country {Id=202, Code= "SVN", Name= "Slovenia", Active= true },
                new Country {Id=203, Code= "SLB", Name= "Solomon Islands", Active= true },
                new Country {Id=204, Code= "SOM", Name= "Somalia", Active= true },
                new Country {Id=205, Code= "ZAF", Name= "South Africa", Active= true },
                new Country {Id=206, Code= "SGS", Name= "South Georgia and the South Sandwich Islands", Active= true },
                new Country {Id=207, Code= "SSD", Name= "South Sudan", Active= true },
                new Country {Id=208, Code= "ESP", Name= "Spain", Active= true },
                new Country {Id=209, Code= "LKA", Name= "Sri Lanka", Active= true },
                new Country {Id=210, Code= "SDN", Name= "Sudan", Active= true },
                new Country {Id=211, Code= "SUR", Name= "Suriname", Active= true },
                new Country {Id=212, Code= "SJM", Name= "Svalbard and Jan Mayen Islands", Active= true },
                new Country {Id=213, Code= "SWZ", Name= "Swaziland", Active= true },
                new Country {Id=214, Code= "SWE", Name= "Sweden", Active= true },
                new Country {Id=215, Code= "CHE", Name= "Switzerland", Active= true },
                new Country {Id=216, Code= "SYR", Name= "Syrian Arab Republic (Syria)", Active= true },
                new Country {Id=217, Code= "TWN", Name= "Taiwan, Republic of China", Active= true },
                new Country {Id=218, Code= "TJK", Name= "Tajikistan", Active= true },
                new Country {Id=219, Code= "TZA", Name= "Tanzania, United Republic of", Active= true },
                new Country {Id=220, Code= "THA", Name= "Thailand", Active= true },
                new Country {Id=221, Code= "TLS", Name= "Timor-Leste", Active= true },
                new Country {Id=222, Code= "TGO", Name= "Togo", Active= true },
                new Country {Id=223, Code= "TKL", Name= "Tokelau", Active= true },
                new Country {Id=224, Code= "TON", Name= "Tonga", Active= true },
                new Country {Id=225, Code= "TTO", Name= "Trinidad and Tobago", Active= true },
                new Country {Id=226, Code= "TUN", Name= "Tunisia", Active= true },
                new Country {Id=227, Code= "TUR", Name= "Turkey", Active= true },
                new Country {Id=228, Code= "TKM", Name= "Turkmenistan", Active= true },
                new Country {Id=229, Code= "TCA", Name= "Turks and Caicos Islands", Active= true },
                new Country {Id=230, Code= "TUV", Name= "Tuvalu", Active= true },
                new Country {Id=231, Code= "UGA", Name= "Uganda", Active= true },
                new Country {Id=232, Code= "UKR", Name= "Ukraine", Active= true },
                new Country {Id=233, Code= "ARE", Name= "United Arab Emirates", Active= true },
                new Country {Id=234, Code= "GBR", Name= "United Kingdom", Active= true },
                new Country {Id=235, Code= "USA", Name= "United States of America", Active= true },
                new Country {Id=236, Code= "UMI", Name= "US Minor Outlying Islands", Active= true },
                new Country {Id=237, Code= "URY", Name= "Uruguay", Active= true },
                new Country {Id=238, Code= "UZB", Name= "Uzbekistan", Active= true },
                new Country {Id=239, Code= "VUT", Name= "Vanuatu", Active= true },
                new Country {Id=240, Code= "VEN", Name= "Venezuela (Bolivarian Republic)", Active= true },
                new Country {Id=241, Code= "VNM", Name= "Viet Nam", Active= true },
                new Country {Id=242, Code= "VIR", Name= "Virgin Islands, US", Active= true },
                new Country {Id=243, Code= "WLF", Name= "Wallis and Futuna Islands", Active= true },
                new Country {Id=244, Code= "ESH", Name= "Western Sahara", Active= true },
                new Country {Id=245, Code= "YEM", Name= "Yemen", Active= true },
                new Country {Id=246, Code= "ZMB", Name= "Zambia", Active= true },
                new Country {Id=247, Code= "ZWE", Name= "Zimbabwe", Active= true }
                );
        }

        /// <summary>
        /// Seeder to add some users by default
        /// in the application
        /// </summary>
        /// <param name="modelBuilder"></param>
        public static void SeedUsers(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<User>().HasData(
                new User { Id = 1, Name = "Ricardo", LastName="Martinez" , Email = "ricardom0490@gmail.com", CountryId = 1, Birthday = new DateTime(1996,01,18), NeedInformation = true, PhoneNumber = 85021379},
                new User { Id = 2, Name = "UserBoombit", LastName = "Costa Rica" ,Email = "example@boombit.com", CountryId = 2, Birthday = new DateTime(2000, 12, 18), NeedInformation = false, PhoneNumber = 25222222 }
                );
        }

        public static void SeedActivity(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Activity>().HasData(
                new Activity { Id = 1, ActivityDescription = "CREATION", CreatedDay = DateTime.Now, UserId = 1},
                new Activity { Id = 2, ActivityDescription = "CREATION", CreatedDay = DateTime.Now, UserId = 2 }
                );
        }
    }
}

