// <auto-generated />
using System;
using Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WebApiBoombit.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20221103184135_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Entities.Models.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ActivityDescription")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("CreatedDay")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActivityDescription = "CREATION",
                            CreatedDay = new DateTime(2022, 11, 3, 12, 41, 35, 818, DateTimeKind.Local).AddTicks(3380),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            ActivityDescription = "CREATION",
                            CreatedDay = new DateTime(2022, 11, 3, 12, 41, 35, 818, DateTimeKind.Local).AddTicks(3380),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Domain.Entities.Models.Country", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Code = "AFG",
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            Code = "ALA",
                            Name = "Aland Islands"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            Code = "ALB",
                            Name = "Albania"
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            Code = "DZA",
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            Code = "ASM",
                            Name = "American Samoa"
                        },
                        new
                        {
                            Id = 6,
                            Active = true,
                            Code = "AND",
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = 7,
                            Active = true,
                            Code = "AGO",
                            Name = "Angola"
                        },
                        new
                        {
                            Id = 8,
                            Active = true,
                            Code = "AIA",
                            Name = "Anguilla"
                        },
                        new
                        {
                            Id = 9,
                            Active = true,
                            Code = "ATA",
                            Name = "Antarctica"
                        },
                        new
                        {
                            Id = 10,
                            Active = true,
                            Code = "ATG",
                            Name = "Antigua and Barbuda"
                        },
                        new
                        {
                            Id = 11,
                            Active = true,
                            Code = "ARG",
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 12,
                            Active = true,
                            Code = "ARM",
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = 13,
                            Active = true,
                            Code = "ABW",
                            Name = "Aruba"
                        },
                        new
                        {
                            Id = 14,
                            Active = true,
                            Code = "AUS",
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 15,
                            Active = true,
                            Code = "AUT",
                            Name = "Austria"
                        },
                        new
                        {
                            Id = 16,
                            Active = true,
                            Code = "AZE",
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = 17,
                            Active = true,
                            Code = "BHS",
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = 18,
                            Active = true,
                            Code = "BHR",
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = 19,
                            Active = true,
                            Code = "BGD",
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = 20,
                            Active = true,
                            Code = "BRB",
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = 21,
                            Active = true,
                            Code = "BLR",
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = 22,
                            Active = true,
                            Code = "BEL",
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = 23,
                            Active = true,
                            Code = "BLZ",
                            Name = "Belize"
                        },
                        new
                        {
                            Id = 24,
                            Active = true,
                            Code = "BEN",
                            Name = "Benin"
                        },
                        new
                        {
                            Id = 25,
                            Active = true,
                            Code = "BMU",
                            Name = "Bermuda"
                        },
                        new
                        {
                            Id = 26,
                            Active = true,
                            Code = "BTN",
                            Name = "Bhutan"
                        },
                        new
                        {
                            Id = 27,
                            Active = true,
                            Code = "BOL",
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = 28,
                            Active = true,
                            Code = "BIH",
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = 29,
                            Active = true,
                            Code = "BWA",
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = 30,
                            Active = true,
                            Code = "BVT",
                            Name = "Bouvet Island"
                        },
                        new
                        {
                            Id = 31,
                            Active = true,
                            Code = "BRA",
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = 32,
                            Active = true,
                            Code = "VGB",
                            Name = "British Virgin Islands"
                        },
                        new
                        {
                            Id = 33,
                            Active = true,
                            Code = "IOT",
                            Name = "British Indian Ocean Territory"
                        },
                        new
                        {
                            Id = 34,
                            Active = true,
                            Code = "BRN",
                            Name = "Brunei Darussalam"
                        },
                        new
                        {
                            Id = 35,
                            Active = true,
                            Code = "BGR",
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = 36,
                            Active = true,
                            Code = "BFA",
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = 37,
                            Active = true,
                            Code = "BDI",
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = 38,
                            Active = true,
                            Code = "KHM",
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = 39,
                            Active = true,
                            Code = "CMR",
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = 40,
                            Active = true,
                            Code = "CAN",
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 41,
                            Active = true,
                            Code = "CPV",
                            Name = "Cape Verde"
                        },
                        new
                        {
                            Id = 42,
                            Active = true,
                            Code = "CYM",
                            Name = "Cayman Islands"
                        },
                        new
                        {
                            Id = 43,
                            Active = true,
                            Code = "CAF",
                            Name = "Central African Republic"
                        },
                        new
                        {
                            Id = 44,
                            Active = true,
                            Code = "TCD",
                            Name = "Chad"
                        },
                        new
                        {
                            Id = 45,
                            Active = true,
                            Code = "CHL",
                            Name = "Chile"
                        },
                        new
                        {
                            Id = 46,
                            Active = true,
                            Code = "CHN",
                            Name = "China"
                        },
                        new
                        {
                            Id = 47,
                            Active = true,
                            Code = "HKG",
                            Name = "Hong Kong, SAR China"
                        },
                        new
                        {
                            Id = 48,
                            Active = true,
                            Code = "MAC",
                            Name = "Macao, SAR China"
                        },
                        new
                        {
                            Id = 49,
                            Active = true,
                            Code = "CXR",
                            Name = "Christmas Island"
                        },
                        new
                        {
                            Id = 50,
                            Active = true,
                            Code = "CCK",
                            Name = "Cocos (Keeling) Islands"
                        },
                        new
                        {
                            Id = 51,
                            Active = true,
                            Code = "COL",
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = 52,
                            Active = true,
                            Code = "COM",
                            Name = "Comoros"
                        },
                        new
                        {
                            Id = 53,
                            Active = true,
                            Code = "COG",
                            Name = "Congo (Brazzaville)"
                        },
                        new
                        {
                            Id = 54,
                            Active = true,
                            Code = "COD",
                            Name = "Congo, (Kinshasa)"
                        },
                        new
                        {
                            Id = 55,
                            Active = true,
                            Code = "COK",
                            Name = "Cook Islands"
                        },
                        new
                        {
                            Id = 56,
                            Active = true,
                            Code = "CRI",
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = 57,
                            Active = true,
                            Code = "CIV",
                            Name = "Côte d'Ivoire"
                        },
                        new
                        {
                            Id = 58,
                            Active = true,
                            Code = "HRV",
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = 59,
                            Active = true,
                            Code = "CUB",
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = 60,
                            Active = true,
                            Code = "CYP",
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = 61,
                            Active = true,
                            Code = "CZE",
                            Name = "Czech Republic"
                        },
                        new
                        {
                            Id = 62,
                            Active = true,
                            Code = "DNK",
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = 63,
                            Active = true,
                            Code = "DJI",
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = 64,
                            Active = true,
                            Code = "DMA",
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = 65,
                            Active = true,
                            Code = "DOM",
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = 66,
                            Active = true,
                            Code = "ECU",
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = 67,
                            Active = true,
                            Code = "EGY",
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = 68,
                            Active = true,
                            Code = "SLV",
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = 69,
                            Active = true,
                            Code = "GNQ",
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = 70,
                            Active = true,
                            Code = "ERI",
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = 71,
                            Active = true,
                            Code = "EST",
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = 72,
                            Active = true,
                            Code = "ETH",
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = 73,
                            Active = true,
                            Code = "FLK",
                            Name = "Falkland Islands (Malvinas)"
                        },
                        new
                        {
                            Id = 74,
                            Active = true,
                            Code = "FRO",
                            Name = "Faroe Islands"
                        },
                        new
                        {
                            Id = 75,
                            Active = true,
                            Code = "FJI",
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = 76,
                            Active = true,
                            Code = "FIN",
                            Name = "Finland"
                        },
                        new
                        {
                            Id = 77,
                            Active = true,
                            Code = "FRA",
                            Name = "France"
                        },
                        new
                        {
                            Id = 78,
                            Active = true,
                            Code = "GUF",
                            Name = "French Guiana"
                        },
                        new
                        {
                            Id = 79,
                            Active = true,
                            Code = "PYF",
                            Name = "French Polynesia"
                        },
                        new
                        {
                            Id = 80,
                            Active = true,
                            Code = "ATF",
                            Name = "French Southern Territories"
                        },
                        new
                        {
                            Id = 81,
                            Active = true,
                            Code = "GAB",
                            Name = "Gabon"
                        },
                        new
                        {
                            Id = 82,
                            Active = true,
                            Code = "GMB",
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = 83,
                            Active = true,
                            Code = "GEO",
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = 84,
                            Active = true,
                            Code = "DEU",
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 85,
                            Active = true,
                            Code = "GHA",
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = 86,
                            Active = true,
                            Code = "GIB",
                            Name = "Gibraltar"
                        },
                        new
                        {
                            Id = 87,
                            Active = true,
                            Code = "GRC",
                            Name = "Greece"
                        },
                        new
                        {
                            Id = 88,
                            Active = true,
                            Code = "GRL",
                            Name = "Greenland"
                        },
                        new
                        {
                            Id = 89,
                            Active = true,
                            Code = "GRD",
                            Name = "Grenada"
                        },
                        new
                        {
                            Id = 90,
                            Active = true,
                            Code = "GLP",
                            Name = "Guadeloupe"
                        },
                        new
                        {
                            Id = 91,
                            Active = true,
                            Code = "GUM",
                            Name = "Guam"
                        },
                        new
                        {
                            Id = 92,
                            Active = true,
                            Code = "GTM",
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = 93,
                            Active = true,
                            Code = "GGY",
                            Name = "Guernsey"
                        },
                        new
                        {
                            Id = 94,
                            Active = true,
                            Code = "GIN",
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = 95,
                            Active = true,
                            Code = "GNB",
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = 96,
                            Active = true,
                            Code = "GUY",
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = 97,
                            Active = true,
                            Code = "HTI",
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = 98,
                            Active = true,
                            Code = "HMD",
                            Name = "Heard and Mcdonald Islands"
                        },
                        new
                        {
                            Id = 99,
                            Active = true,
                            Code = "VAT",
                            Name = "Holy See (Vatican City State)"
                        },
                        new
                        {
                            Id = 100,
                            Active = true,
                            Code = "HND",
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = 101,
                            Active = true,
                            Code = "HUN",
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = 102,
                            Active = true,
                            Code = "ISL",
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = 103,
                            Active = true,
                            Code = "IND",
                            Name = "India"
                        },
                        new
                        {
                            Id = 104,
                            Active = true,
                            Code = "IDN",
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = 105,
                            Active = true,
                            Code = "IRN",
                            Name = "Iran, Islamic Republic of"
                        },
                        new
                        {
                            Id = 106,
                            Active = true,
                            Code = "IRQ",
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = 107,
                            Active = true,
                            Code = "IRL",
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = 108,
                            Active = true,
                            Code = "IMN",
                            Name = "Isle of Man"
                        },
                        new
                        {
                            Id = 109,
                            Active = true,
                            Code = "ISR",
                            Name = "Israel"
                        },
                        new
                        {
                            Id = 110,
                            Active = true,
                            Code = "ITA",
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 111,
                            Active = true,
                            Code = "JAM",
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = 112,
                            Active = true,
                            Code = "JPN",
                            Name = "Japan"
                        },
                        new
                        {
                            Id = 113,
                            Active = true,
                            Code = "JEY",
                            Name = "Jersey"
                        },
                        new
                        {
                            Id = 114,
                            Active = true,
                            Code = "JOR",
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = 115,
                            Active = true,
                            Code = "KAZ",
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = 116,
                            Active = true,
                            Code = "KEN",
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = 117,
                            Active = true,
                            Code = "KIR",
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = 118,
                            Active = true,
                            Code = "PRK",
                            Name = "Korea (North)"
                        },
                        new
                        {
                            Id = 119,
                            Active = true,
                            Code = "KOR",
                            Name = "Korea (South)"
                        },
                        new
                        {
                            Id = 120,
                            Active = true,
                            Code = "KWT",
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = 121,
                            Active = true,
                            Code = "KGZ",
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = 122,
                            Active = true,
                            Code = "LAO",
                            Name = "Lao PDR"
                        },
                        new
                        {
                            Id = 123,
                            Active = true,
                            Code = "LVA",
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = 124,
                            Active = true,
                            Code = "LBN",
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = 125,
                            Active = true,
                            Code = "LSO",
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = 126,
                            Active = true,
                            Code = "LBR",
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = 127,
                            Active = true,
                            Code = "LBY",
                            Name = "Libya"
                        },
                        new
                        {
                            Id = 128,
                            Active = true,
                            Code = "LIE",
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = 129,
                            Active = true,
                            Code = "LTU",
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = 130,
                            Active = true,
                            Code = "LUX",
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = 131,
                            Active = true,
                            Code = "MKD",
                            Name = "Macedonia, Republic of"
                        },
                        new
                        {
                            Id = 132,
                            Active = true,
                            Code = "MDG",
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = 133,
                            Active = true,
                            Code = "MWI",
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = 134,
                            Active = true,
                            Code = "MYS",
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = 135,
                            Active = true,
                            Code = "MDV",
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = 136,
                            Active = true,
                            Code = "MLI",
                            Name = "Mali"
                        },
                        new
                        {
                            Id = 137,
                            Active = true,
                            Code = "MLT",
                            Name = "Malta"
                        },
                        new
                        {
                            Id = 138,
                            Active = true,
                            Code = "MHL",
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            Id = 139,
                            Active = true,
                            Code = "MTQ",
                            Name = "Martinique"
                        },
                        new
                        {
                            Id = 140,
                            Active = true,
                            Code = "MRT",
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = 141,
                            Active = true,
                            Code = "MUS",
                            Name = "Mauritius"
                        },
                        new
                        {
                            Id = 142,
                            Active = true,
                            Code = "MYT",
                            Name = "Mayotte"
                        },
                        new
                        {
                            Id = 143,
                            Active = true,
                            Code = "MEX",
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = 144,
                            Active = true,
                            Code = "FSM",
                            Name = "Micronesia, Federated States of"
                        },
                        new
                        {
                            Id = 145,
                            Active = true,
                            Code = "MDA",
                            Name = "Moldova"
                        },
                        new
                        {
                            Id = 146,
                            Active = true,
                            Code = "MCO",
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = 147,
                            Active = true,
                            Code = "MNG",
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = 148,
                            Active = true,
                            Code = "MNE",
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = 149,
                            Active = true,
                            Code = "MSR",
                            Name = "Montserrat"
                        },
                        new
                        {
                            Id = 150,
                            Active = true,
                            Code = "MAR",
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = 151,
                            Active = true,
                            Code = "MOZ",
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = 152,
                            Active = true,
                            Code = "MMR",
                            Name = "Myanmar"
                        },
                        new
                        {
                            Id = 153,
                            Active = true,
                            Code = "NAM",
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = 154,
                            Active = true,
                            Code = "NRU",
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = 155,
                            Active = true,
                            Code = "NPL",
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = 156,
                            Active = true,
                            Code = "NLD",
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = 157,
                            Active = true,
                            Code = "ANT",
                            Name = "Netherlands Antilles"
                        },
                        new
                        {
                            Id = 158,
                            Active = true,
                            Code = "NCL",
                            Name = "New Caledonia"
                        },
                        new
                        {
                            Id = 159,
                            Active = true,
                            Code = "NZL",
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = 160,
                            Active = true,
                            Code = "NIC",
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = 161,
                            Active = true,
                            Code = "NER",
                            Name = "Niger"
                        },
                        new
                        {
                            Id = 162,
                            Active = true,
                            Code = "NGA",
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = 163,
                            Active = true,
                            Code = "NIU",
                            Name = "Niue"
                        },
                        new
                        {
                            Id = 164,
                            Active = true,
                            Code = "NFK",
                            Name = "Norfolk Island"
                        },
                        new
                        {
                            Id = 165,
                            Active = true,
                            Code = "MNP",
                            Name = "Northern Mariana Islands"
                        },
                        new
                        {
                            Id = 166,
                            Active = true,
                            Code = "NOR",
                            Name = "Norway"
                        },
                        new
                        {
                            Id = 167,
                            Active = true,
                            Code = "OMN",
                            Name = "Oman"
                        },
                        new
                        {
                            Id = 168,
                            Active = true,
                            Code = "PAK",
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = 169,
                            Active = true,
                            Code = "PLW",
                            Name = "Palau"
                        },
                        new
                        {
                            Id = 170,
                            Active = true,
                            Code = "PSE",
                            Name = "Palestinian Territory"
                        },
                        new
                        {
                            Id = 171,
                            Active = true,
                            Code = "PAN",
                            Name = "Panama"
                        },
                        new
                        {
                            Id = 172,
                            Active = true,
                            Code = "PNG",
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Id = 173,
                            Active = true,
                            Code = "PRY",
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = 174,
                            Active = true,
                            Code = "PER",
                            Name = "Peru"
                        },
                        new
                        {
                            Id = 175,
                            Active = true,
                            Code = "PHL",
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = 176,
                            Active = true,
                            Code = "PCN",
                            Name = "Pitcairn"
                        },
                        new
                        {
                            Id = 177,
                            Active = true,
                            Code = "POL",
                            Name = "Poland"
                        },
                        new
                        {
                            Id = 178,
                            Active = true,
                            Code = "PRT",
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 179,
                            Active = true,
                            Code = "PRI",
                            Name = "Puerto Rico"
                        },
                        new
                        {
                            Id = 180,
                            Active = true,
                            Code = "QAT",
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = 181,
                            Active = true,
                            Code = "REU",
                            Name = "Réunion"
                        },
                        new
                        {
                            Id = 182,
                            Active = true,
                            Code = "ROU",
                            Name = "Romania"
                        },
                        new
                        {
                            Id = 183,
                            Active = true,
                            Code = "RUS",
                            Name = "Russian Federation"
                        },
                        new
                        {
                            Id = 184,
                            Active = true,
                            Code = "RWA",
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = 185,
                            Active = true,
                            Code = "BLM",
                            Name = "Saint-Barthélemy"
                        },
                        new
                        {
                            Id = 186,
                            Active = true,
                            Code = "SHN",
                            Name = "Saint Helena"
                        },
                        new
                        {
                            Id = 187,
                            Active = true,
                            Code = "KNA",
                            Name = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            Id = 188,
                            Active = true,
                            Code = "LCA",
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            Id = 189,
                            Active = true,
                            Code = "MAF",
                            Name = "Saint-Martin (French part)"
                        },
                        new
                        {
                            Id = 190,
                            Active = true,
                            Code = "SPM",
                            Name = "Saint Pierre and Miquelon"
                        },
                        new
                        {
                            Id = 191,
                            Active = true,
                            Code = "VCT",
                            Name = "Saint Vincent and Grenadines"
                        },
                        new
                        {
                            Id = 192,
                            Active = true,
                            Code = "WSM",
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = 193,
                            Active = true,
                            Code = "SMR",
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = 194,
                            Active = true,
                            Code = "STP",
                            Name = "Sao Tome and Principe"
                        },
                        new
                        {
                            Id = 195,
                            Active = true,
                            Code = "SAU",
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 196,
                            Active = true,
                            Code = "SEN",
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = 197,
                            Active = true,
                            Code = "SRB",
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = 198,
                            Active = true,
                            Code = "SYC",
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = 199,
                            Active = true,
                            Code = "SLE",
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Id = 200,
                            Active = true,
                            Code = "SGP",
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = 201,
                            Active = true,
                            Code = "SVK",
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = 202,
                            Active = true,
                            Code = "SVN",
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = 203,
                            Active = true,
                            Code = "SLB",
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            Id = 204,
                            Active = true,
                            Code = "SOM",
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = 205,
                            Active = true,
                            Code = "ZAF",
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = 206,
                            Active = true,
                            Code = "SGS",
                            Name = "South Georgia and the South Sandwich Islands"
                        },
                        new
                        {
                            Id = 207,
                            Active = true,
                            Code = "SSD",
                            Name = "South Sudan"
                        },
                        new
                        {
                            Id = 208,
                            Active = true,
                            Code = "ESP",
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 209,
                            Active = true,
                            Code = "LKA",
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = 210,
                            Active = true,
                            Code = "SDN",
                            Name = "Sudan"
                        },
                        new
                        {
                            Id = 211,
                            Active = true,
                            Code = "SUR",
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = 212,
                            Active = true,
                            Code = "SJM",
                            Name = "Svalbard and Jan Mayen Islands"
                        },
                        new
                        {
                            Id = 213,
                            Active = true,
                            Code = "SWZ",
                            Name = "Swaziland"
                        },
                        new
                        {
                            Id = 214,
                            Active = true,
                            Code = "SWE",
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = 215,
                            Active = true,
                            Code = "CHE",
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = 216,
                            Active = true,
                            Code = "SYR",
                            Name = "Syrian Arab Republic (Syria)"
                        },
                        new
                        {
                            Id = 217,
                            Active = true,
                            Code = "TWN",
                            Name = "Taiwan, Republic of China"
                        },
                        new
                        {
                            Id = 218,
                            Active = true,
                            Code = "TJK",
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = 219,
                            Active = true,
                            Code = "TZA",
                            Name = "Tanzania, United Republic of"
                        },
                        new
                        {
                            Id = 220,
                            Active = true,
                            Code = "THA",
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = 221,
                            Active = true,
                            Code = "TLS",
                            Name = "Timor-Leste"
                        },
                        new
                        {
                            Id = 222,
                            Active = true,
                            Code = "TGO",
                            Name = "Togo"
                        },
                        new
                        {
                            Id = 223,
                            Active = true,
                            Code = "TKL",
                            Name = "Tokelau"
                        },
                        new
                        {
                            Id = 224,
                            Active = true,
                            Code = "TON",
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = 225,
                            Active = true,
                            Code = "TTO",
                            Name = "Trinidad and Tobago"
                        },
                        new
                        {
                            Id = 226,
                            Active = true,
                            Code = "TUN",
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = 227,
                            Active = true,
                            Code = "TUR",
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 228,
                            Active = true,
                            Code = "TKM",
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = 229,
                            Active = true,
                            Code = "TCA",
                            Name = "Turks and Caicos Islands"
                        },
                        new
                        {
                            Id = 230,
                            Active = true,
                            Code = "TUV",
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = 231,
                            Active = true,
                            Code = "UGA",
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = 232,
                            Active = true,
                            Code = "UKR",
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 233,
                            Active = true,
                            Code = "ARE",
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = 234,
                            Active = true,
                            Code = "GBR",
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = 235,
                            Active = true,
                            Code = "USA",
                            Name = "United States of America"
                        },
                        new
                        {
                            Id = 236,
                            Active = true,
                            Code = "UMI",
                            Name = "US Minor Outlying Islands"
                        },
                        new
                        {
                            Id = 237,
                            Active = true,
                            Code = "URY",
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = 238,
                            Active = true,
                            Code = "UZB",
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = 239,
                            Active = true,
                            Code = "VUT",
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = 240,
                            Active = true,
                            Code = "VEN",
                            Name = "Venezuela (Bolivarian Republic)"
                        },
                        new
                        {
                            Id = 241,
                            Active = true,
                            Code = "VNM",
                            Name = "Viet Nam"
                        },
                        new
                        {
                            Id = 242,
                            Active = true,
                            Code = "VIR",
                            Name = "Virgin Islands, US"
                        },
                        new
                        {
                            Id = 243,
                            Active = true,
                            Code = "WLF",
                            Name = "Wallis and Futuna Islands"
                        },
                        new
                        {
                            Id = 244,
                            Active = true,
                            Code = "ESH",
                            Name = "Western Sahara"
                        },
                        new
                        {
                            Id = 245,
                            Active = true,
                            Code = "YEM",
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = 246,
                            Active = true,
                            Code = "ZMB",
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = 247,
                            Active = true,
                            Code = "ZWE",
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<bool>("NeedInformation")
                        .HasColumnType("bit");

                    b.Property<long?>("PhoneNumber")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthday = new DateTime(1996, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryId = 1,
                            Email = "ricardom0490@gmail.com",
                            LastName = "Martinez",
                            Name = "Ricardo",
                            NeedInformation = true,
                            PhoneNumber = 85021379L
                        },
                        new
                        {
                            Id = 2,
                            Birthday = new DateTime(2000, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CountryId = 2,
                            Email = "example@boombit.com",
                            LastName = "Costa Rica",
                            Name = "UserBoombit",
                            NeedInformation = false,
                            PhoneNumber = 25222222L
                        });
                });

            modelBuilder.Entity("Domain.Entities.Models.Activity", b =>
                {
                    b.HasOne("Domain.Entities.Models.User", "User")
                        .WithMany("Activities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Models.User", b =>
                {
                    b.HasOne("Domain.Entities.Models.Country", "Country")
                        .WithMany("users")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Domain.Entities.Models.Country", b =>
                {
                    b.Navigation("users");
                });

            modelBuilder.Entity("Domain.Entities.Models.User", b =>
                {
                    b.Navigation("Activities");
                });
#pragma warning restore 612, 618
        }
    }
}
